// <auto-generated />
using System;
using GestionMagasin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionMagasin.Migrations
{
    [DbContext(typeof(TpDbContext))]
    [Migration("20200211103634_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("GestionMagasin.model.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateSortie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Poids")
                        .HasColumnType("REAL");

                    b.Property<float>("PrixInitial")
                        .HasColumnType("REAL");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("GestionMagasin.model.Etagere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSecteur")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PoidsMaximum")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IdSecteur");

                    b.ToTable("Etageres");
                });

            modelBuilder.Entity("GestionMagasin.model.PositionMagasin", b =>
                {
                    b.Property<int>("IdEtagere")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdArticle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdEtagere", "IdArticle");

                    b.HasIndex("IdArticle");

                    b.ToTable("PositionMagasin");
                });

            modelBuilder.Entity("GestionMagasin.model.Secteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Secteurs");
                });

            modelBuilder.Entity("GestionMagasin.model.Etagere", b =>
                {
                    b.HasOne("GestionMagasin.model.Secteur", "Secteur")
                        .WithMany("ListEtagere")
                        .HasForeignKey("IdSecteur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionMagasin.model.PositionMagasin", b =>
                {
                    b.HasOne("GestionMagasin.model.Article", "Article")
                        .WithMany("ListPositions")
                        .HasForeignKey("IdArticle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionMagasin.model.Etagere", "Etagere")
                        .WithMany("ListPositions")
                        .HasForeignKey("IdEtagere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
